import type { OpenTabsSnapshot, TabDetailView } from '../../../shared/open-tabs';

export function createOpenTabsSlice() {
  return {
    openTabsOpen: false,
    openTabsLoading: false,
    openTabsBusy: false,
    openTabsStatusMessage: 'Listo para operar mesas VIP.' as string,
    openTabsStatusKind: 'info' as 'info' | 'success' | 'error',
    openTabsSnapshot: { tables: [], tabs: [] } as OpenTabsSnapshot,
    openTabsSelectedTableId: '',
    openTabsSelectedTabId: '',
    openTabsDetail: null as TabDetailView | null,
    openTabsSelectedProductId: '',
    openTabsQtyInput: '1',
    openTabsNotesInput: '',
    openTabsShowSentLines: false,
    openTabsGenerateCountInput: '12',
    openTabsGeneratePrefixInput: 'Mesa',
    openTabsGenerateStartAtInput: '1',
    openTabsPaymentMethod: 'efectivo' as 'efectivo' | 'tarjeta' | 'employee',
    openTabsForceRefresh: false,
    openTabsIsPosMaster: false,
    tableModeEnabled: false,
    tableSelectorOpen: false,
    tableSelectorSelectedTableId: '',
    tablesSettingsOpen: false,
    tablesSettingsLoading: false,
    tablesSettingsBusy: false,
    tablesSettingsRows: [] as OpenTabsSnapshot['tables'],
    tablesSettingsPreview: '',
    tablesSettingsConfirmText: '',
    tablesSettingsGeneratePrefix: 'Mesa',
    tablesSettingsGenerateCount: '12',
    tablesSettingsGenerateStartAt: '1',
    tabKitchenHistoryOpen: false,
    tabKitchenHistoryLoading: false,
    tabKitchenHistoryBusy: false,
    tabKitchenHistoryTabId: '',
    tabKitchenHistoryDetail: null as TabDetailView | null,
    tabKitchenHistoryStatusMessage: 'Selecciona una comanda para operar.' as string,
    tabKitchenHistoryStatusKind: 'info' as 'info' | 'success' | 'error',
    openTabs: {
      version: 0,
    },
  };
}
