export const IPC_CHANNELS = {
  PRINT_V2: 'pos:print:v2',
  PRINT_JOBS_LIST: 'pos:print:jobs:list',
  PRINT_CONFIG_GET: 'pos:print:config:get',
  PRINT_CONFIG_SET: 'pos:print:config:set',
  CATALOG_GET: 'pos:catalog:get',
  CATALOG_SYNC: 'pos:catalog:sync',
  CATALOG_ASSIGN_BARCODE: 'pos:catalog:assign-barcode',
  SALE_CREATE_AND_PRINT: 'pos:sale:create-and-print',
  ORDER_HISTORY_LIST: 'pos:orders:history:list',
  ORDER_REPRINT: 'pos:orders:reprint',
  ORDER_CANCEL: 'pos:orders:cancel',
  OUTBOX_SYNC: 'pos:outbox:sync',
  OUTBOX_SYNC_STATUS: 'pos:outbox:sync-status',
  OUTBOX_STATUS_EVENT: 'pos:outbox:status',
  DEBUG_GET_STATE: 'pos:debug:getState',
  OPEN_TABS_SNAPSHOT: 'pos:open-tabs:snapshot',
  OPEN_TABS_DETAIL: 'pos:open-tabs:detail',
  OPEN_TABS_CONFIGURE_TABLES: 'pos:open-tabs:configure-tables',
  OPEN_TABS_TABLES_LIST: 'pos:open-tabs:tables:list',
  OPEN_TABS_TABLES_UPDATE: 'pos:open-tabs:tables:update',
  OPEN_TABS_TABLES_TOGGLE: 'pos:open-tabs:tables:toggle',
  OPEN_TABS_TABLES_DELETE: 'pos:open-tabs:tables:delete',
  OPEN_TABS_TABLES_REORDER: 'pos:open-tabs:tables:reorder',
  OPEN_TABS_OPEN: 'pos:open-tabs:open',
  OPEN_TABS_ADD_ITEM: 'pos:open-tabs:add-item',
  OPEN_TABS_UPDATE_QTY: 'pos:open-tabs:update-qty',
  OPEN_TABS_REMOVE_ITEM: 'pos:open-tabs:remove-item',
  OPEN_TABS_KITCHEN_SEND: 'pos:open-tabs:kitchen-send',
  OPEN_TABS_KITCHEN_REPRINT: 'pos:open-tabs:kitchen-reprint',
  OPEN_TABS_KITCHEN_CANCEL: 'pos:open-tabs:kitchen-cancel',
  OPEN_TABS_CLOSE_PAID: 'pos:open-tabs:close-paid',
  OPEN_TABS_CANCEL: 'pos:open-tabs:cancel',
  OPEN_TABS_SYNC: 'pos:open-tabs:sync',
  OPEN_TABS_IS_POS_MASTER: 'pos:open-tabs:is-pos-master',
  RUNTIME_CONFIG_GET: 'pos:runtime-config:get',
  RUNTIME_CONFIG_SET: 'pos:runtime-config:set',
  SCANNER_DATA: 'pos:scanner:data',
  SCAN_CAPTURE_DATA: 'pos:scan',
  SCAN_CAPTURE_SET_CONTEXT: 'pos:scan:setContext',
  SCAN_CAPTURE_SET_ENABLED: 'pos:scan:setEnabled',
  SCAN_CAPTURE_SET_SETTINGS: 'pos:scan:setSettings',
  SCAN_CAPTURE_GET_DEBUG_STATE: 'pos:scan:getDebugState',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
